[freetz-2.0] merge (refs #2072)
r10427 | cuma | 2013-04-21 16:00:07 GMT+01:00

rc.mod: use "ifconfig" for ipv6, "ip" is not mandatory
----------------------------------------------------------------------------
r10418 | er13 | 2013-04-20 13:05:31 GMT+01:00

remove-dsld-patch:
 * do not remove libdsl.so if firmware contains libwylg.so and libwylg.so specifies libdsl.so as NEEDED
 * libwylg.so is required by ahamailer, provided we have a remove patch for ahamailer we can probably remove libdsl.so
 * fixes #2080

----------------------------------------------------------------------------
r10417 | er13 | 2013-04-20 12:51:47 GMT+01:00

remove-dsld-patch:
 * remove both /usr/share/ctlmgr/libdsl.so and all symlinks to it /lib/libdsl.so*
 * refs #2080

----------------------------------------------------------------------------
r10412 | er13 | 2013-04-20 11:39:56 GMT+01:00

freetz_functions:
 * add yet another NEEDED-entries related function - isNeededEntry
 * refs #2078

----------------------------------------------------------------------------
r10370 | er13 | 2013-04-14 10:32:46 GMT+01:00

openvpn:
 * revert r10369, do "make menuconfig" after clean checkout

----------------------------------------------------------------------------
r10369 | cuma | 2013-04-14 02:34:01 GMT+01:00

openvpn: fix "make openvpn-precompiled" on a clean checkout
{{{
...
configure: error:  ssl is required but missing

ERROR: Build failed.
}}}
----------------------------------------------------------------------------

git-svn-id: file:///var/svn/freetz/branches/freetz-stable-2.0@10432 149334a1-2f27-0410-a3b9-fc62619ac1e6